text hero page
fabi1989/furnishop pull request #2
Opened 2022-08-16 21:39 UTC by fabi1989

@well1791 el textooo!

2022-08-16 21:39 UTC, fabi1989 commented
me falta el boton!

2022-08-17 13:25 UTC, well1791 requested changes
buen trabajo pero veo que aun usas mucho el position absolute, trata de no usarlo y en lugar de eso mas bien usa margin

2022-08-17 13:25 UTC, well1791 commented on style.css
> +  padding: 16px, 80px, 16px, 80px;
esto es un error.. el padding se separa por espacios no por comas

2022-08-17 13:25 UTC, well1791 commented on style.css
> +  gap: 10px;
esta propiedad no sirve sola.. necesitas un `display: flex` al menos

2022-08-18 22:24 UTC, fabi1989 commented on style.css
> +  padding: 16px, 80px, 16px, 80px;
listo!

2022-08-18 22:55 UTC, fabi1989 commented on style.css
> +  gap: 10px;
listo!

2022-08-19 02:43 UTC, well1791 approved these changes

2022-08-19 16:37 UTC, merged